baseURL = '/'
languageCode = 'en-us'
title = "Matthew Sigmond's Website"
theme = 'mainroad'

[Author]
    name = "Matthew Sigmond"

[Params]
    description = "Matthew Sigmond's personal website"
    copyright = "Matthew Sigmond"
    mainSections = ['homepage']
    
[Params.style.vars]
    highlightColor = "#FF5349"

[Params.sidebar]
    widgets = ["search", "social"]
    home = "right"
    list = "right"
    single = "right"

[Params.widgets.social]
twitter = "matthew28845"
github = "matthew28845"

[markup.goldmark.renderer]
 unsafe = true