baseURL = '/'
languageCode = 'en-us'
title = "Matthew Sigmond's Website"
theme = 'mainroad'

[Author]
    name = "Matthew Sigmond"

[Params]
    description = "Matthew Sigmond's personal website"
    copyright = "Matthew Sigmond"
    mainSections = ['homepage']
    post_meta = ["author", "date", "categories", "translations"] # Order of post meta information    
    
[Params.style.vars]
    highlightColor = "#FF5349"

[Params.sidebar]
    widgets = ["search", "social"]
    home = "right"
    list = "right"
    single = "right"

[Params.widgets.social]
    instagram = "matthew28845"
    twitter = "matthew28845"
    github = "matthew28845"

[[Params.widgets.social.custom]]
  title = "Mastodon"
  url = "https://layer8.space/@matthew28845"
  icon = "mastodon.svg"

[[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://youtube.com/user/matthew28845"
  icon = "youtube-svgrepo-com.svg"

[Params.thumbnail]
  visibility = ["list"] # Control thumbnail visibility

[markup.goldmark.renderer]
 unsafe = true

[Params.logo]
  image = "img/profilepic2.png"
  title = "Matthew Sigmond's Website"