baseURL = '/'
languageCode = 'en-us'
title = "Matthew Sigmond's Personal Website"
theme = 'mainroad'

[Site.Params.Author]
    name = "Matt Sigmond"

[Site.Params.baseURL]
    url = "https://matthewsigmond.com"

[Params]
    description = "Matthew Sigmond's personal website"
    copyright = "Matthew Sigmond"
    mainSections = ["homepage", "blog", "photography", "post"]
    post_meta = ["author", "date", "categories", "translations"] # Order of post meta information    
    sectionPagesMenu = 'main'
    
[Params.style.vars]
    highlightColor = "#FF4F00"

[Params.sidebar]
    widgets = ["search", "social", "recent"]
    home = "right"
    list = "right"
    single = "right"

[Params.widgets.social]
    instagram = "matthewsigmond"
    github = "matthew28845"
    linkedin = "matthew-sigmond-39158b27b"

[[Params.widgets.social.custom]]
  title = "Mastodon"
  url = "https://layer8.space/@matthew28845"
  icon = "svg/mastodon-logo-white.svg"

[Params.widgets.recent]
  cached = true

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[markup.goldmark.renderer]
 unsafe = true

[Params.logo]
  title = "Matthew Sigmond"
  image = "/posts/photography/images/headshot.png"